### ISSUE TITLE
Migrate to .NET 5 when released

### ISSUE THREAD

**Issue by Odonno** [Odonno/AspNetCore.FeatureManagement.UI#9]

**Comment by solutions-simplified** [comment]
@Odonno  - thanks for the neat library. I'm currently evaluating this as a potential solution for one of my fun projects. I was curious if you are still working on getting the project up to .NET 5.

I hope all is well!

**Comment by Odonno** [comment]
Well, hello there.

Time flies, indeed. I will have to find some time to do the migration but yep, it is still something I want to do next.

You're talking about .NET 5 but we are now on .NET 6. Is it a requirement for you to be on 5 or could we skip it?

**Comment by solutions-simplified** [comment]
Hi David,

 

.NET 5 would be good 😊

 

But having both available wouldn’t hurt for other developers. You the best!

**Comment by Odonno** [comment]
Hi again,

A new version of the package is now available.

Hope you'll like it!
